### ISSUE TITLE
Touch project does not build

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross-Forms#20]
Because of the System.Core and System.Runtime references in the project, I cannot build the Touch project in VS2013.

When these two references are there, I get the following error when building:

```
Error	1	The type 'System.ComponentModel.INotifyPropertyChanged' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	C:\vcs\git\MvvmCross-Forms\Cirrious.MvvmCross.Forms.Presenter.Touch\MvxFormsTouchPagePresenter.cs	22	16	Cirrious.MvvmCross.Forms.Presenter.Touch
```

**Comment by PeterBurke** [comment]
Hi Tomasz

I have had the problem before.

For example in the Android csproj for the last two Samples that were in my PR there are these references:

```
    <Reference Include="System" />
    <Reference Include="System.ObjectModel" />
    <Reference Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Runtime.dll" />
    <Reference Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.IO.dll" />
    <Reference Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Net.Primitives.dll" />
    <Reference Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Net.Requests.dll" />
    <Reference Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll" />
    <Reference Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Threading.Tasks.dll" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Core" />
    <Reference Include="Mono.Android" />
    <Reference Include="Mono.Android.Export" />
```
Notice that the reference that it is complaining about is in there:
```
<Reference Include="System.ObjectModel" />
```

There are other references as well including references to Xamarin façade assemblies that stop VS complaining about other issues.

Not sure why these references sometimes drop out, especially when switching between different versions of VS.

Just a thought, did you upgrade to VS 2013 Release 5 (released about a week ago)? Some of the issues have been fixed in Release 5.

I am taking a break right now but plan to put Xamarin UI test into the Samples plus I have a package of interesting stuff I developed a couple of months back. There is still a lot of work to be done to get samples and wiki for plugins, plus work on the MvvMCross web site.

**Comment by Cheesebaron** [comment]
I am on on Update 5, yes.

Simply removing the references fixes the build problem. I don't have VS2015 installed so don't know about it there, but why are those references needed in the first place?

**Comment by PeterBurke** [comment]
I am not sure. I put the Xamarin Façade references into the project during my testing and PR generation phase. I use a second computer that has VS2013 Release 5 and fix all compile errors. If it errors about System.ObjectModel then I link it in. The façade references came up as warning messages with a recommendation they be included as references.

As for System.ObjectModel it is definitely needed in the PCL project because it defines the INotifyPropertyChanged interface, and the Android project has a reference to the PCL so MSBUILD will expect that System.ObjectModel be linked as well so that the bin directory has everything that it needs.

Possibly recompiling the PCL would pull System.ObjectModel into the PCL bin and then the error would go away because the Android project would find it there.

**Comment by Cheesebaron** [comment]
It really depends on the profile whether System.ObjectModel is needed to be referenced explicitly or not. Most of my projects I never reference it and I have access to ICommand and INotifyPropertyChanged even so.

Could it be that your environment is broken?

**Comment by PeterBurke** [comment]
If the compiler complains about something is the compiler broken.

Actually my sensitivity on this issue has more to do with having released a PR previously that compiled OK for me but then the reviewer complained it did not work for him, he later said that it is so easy to fix these issues, but at the time he was concerned about others loading projects that don't compile out of the box.

So with this last PR, everything compiled first time. But then I looked closer and attempted fix warnings as well as errors. The reviewer had no issues that time around, it compiled first time for him too, so mission accomplished.

**Comment by martijn00** [comment]
I found out that this is a bug in Xamarin: https://bugzilla.xamarin.com/show_bug.cgi?id=32622
When that update arrives this should be fixed automatically.
