### ISSUE TITLE
Adding Cirrious.MvvmCross.Forms.Presenter Fails

### ISSUE THREAD

**Issue by acastr7** [MvvmCross/MvvmCross-Forms#23]
Trying to add nuget package Cirrious.MvvmCross.Forms.Presenter in Xamarin Studio but when I do I get the error below.

Adding Cirrious.MvvmCross.Forms.Presenter...
Attempting to resolve dependency 'MvvmCross.HotTuna.MvvmCrossLibraries (≥ 4.0.0-beta2)'.
Downloading MvvmCross.HotTuna.MvvmCrossLibraries 4.0.0-beta2...
'MvvmCross.HotTuna.MvvmCrossLibraries' already has a dependency defined for 'MvvmCross.HotTuna.CrossCore'.

**Comment by Cheesebaron** [comment]
Old version of NuGet. Complain to Xamarin.

**Comment by martijn00** [comment]
For more info see: https://github.com/MvvmCross/MvvmCross/issues/1088#issuecomment-132765389

**Comment by PeterBurke** [comment]
Hi Tomasz, since you are second most frequent blogger on the Xamarin blog, you just might have to answer this one again! Just kidding!

My automated testing efforts have progressed. I already have a tool that will start and stop the Android emulator for the simulated Droid device you want to test, plus compile and install the latest APK, before proceeding to the automated tests.

Now I am trying to do the same thing for iOS. What I have started playing around with is a new tool available from Microsoft https://code.visualstudio.com/ this is available for Windows, Linux and OS X and with it you can create a web server.

So now I can run this server on my Mac and from the Windows box kick off remote compilation of the Nunit based test DLL and then run it off line and return the results as an XML file. Before doing this I can do a remote build of the APK from the windows box, this uses the Xamarin build host. Also on the Mac you can tell the Xamarin.UITest which device you want to simulate when you start the test, and UI test brings up the simulator and loads the correct device.

**Comment by Cheesebaron** [comment]
Not sure what to answer, I don't see a question there @PeterBurke?
